unit constantes;

interface

const
  EFETIVO_JOGADOR = 20;
  EFETIVO_INIMIGO = 20;
  DISTANCIA_CENTRO = 35;
  TAMANHO_PERSONAGEM = 0.04;
  LAG_ATAQUE = 12;
  MAX_RODADAS_SEM_MOVIMENTO = 10;
  ESPACAMENTO_INICIAL = 2;
  CLASSE_DE_ARMADURA = 15;
  PONTOS_DE_VIDA = 40;
  PONTOS_DE_VIDA_LIDER = 400;
  VELOCIDADE_CAMINHADA = 0.07;
  VELOCIDADE_CORRIDA = 0.15;
  ANGULO_VIRADA = 7.0;

  PESO_COESAO = 1;
  PESO_ALINHAMENTO = 0;
  PESO_SEPARACAO = 4;
  PESO_OFENSIVO = 3;
  PESO_OFENSIVO_LIDER = 9;
  PESO_LIDER = 2;
  VITALIDADE_MINIMA_CORRIDA = 20;

  RAIO_VISAO = 400;
  ANGULO_VISAO = 210;


implementation

end.
